### ISSUE TITLE
Misidentification of iPhone Mobile as Tablet with specific user agents

### ISSUE THREAD

**Issue by nicskitt** [hisorange/browser-detect#102]
The following in-app IOS user agents are being identified as Tablet when they are iPhone.

Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 [FBAN/FBIOS;FBAV/199.0.0.69.98;FBBV/132813153;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iOS;FBSV/12.1.4;FBSS/3;FBCR/Rogers;FBID/phone;FBLC/en_US;FBOP/5;FBRV/135011850]

Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16C101 [FBAN/FBIOS;FBAV/207.0.0.48.100;FBBV/141048683;FBDV/iPhone10,5;FBMD/iPhone;FBSN/iOS;FBSV/12.1.2;FBSS/3;FBCR/Rogers;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]

Under Laravel 5.7.

Accessing the underlying mobiledetect library correctly identifies the agents as Mobile.

**Comment by hisorange** [comment]
Sadly the mobiledetect isn't reliable all the time. That is why multiple library has to agree on such a topic. Edge cases like this happens but on the global number the common agreement yields better results :/
