### ISSUE TITLE
Call to undefined method DeviceDetector\Parser\Client\Browser::browserName()

### ISSUE THREAD

**Issue by Hretic** [hisorange/browser-detect#103]
hi , for some reason most of the methods in documentation doesn't work 

use DeviceDetector\Parser\Client\Browser;
 dump( Browser::browserName() );

error

(1/1) FatalErrorExceptionCall to undefined method DeviceDetector\Parser\Client\Browser::browserName()
--
in HomeController.php line 28
at FatalErrorException->__construct()in HandleExceptions.php line 138
at HandleExceptions->fatalExceptionFromError()in HandleExceptions.php line 123
at HandleExceptions->handleShutdown()in HandleExceptions.php
at HomeController->index()in Controller.php line 55
at call_user_func_array:{D:\wamp\www\gatewayMiddle\laravel\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:55}()in Controller.php line 55
at Controller->callAction()in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch()in Route.php line 204
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}()in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}()in Client.php line 81
at Client->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in SubstituteBindings.php line 41
at SubstituteBindings->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in StartSession.php line 64
at StartSession->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in EncryptCookies.php line 59
at EncryptCookies->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in Pipeline.php line 102
at Pipeline->then()in Router.php line 574
at Router->runRouteWithinStack()in Router.php line 533
at Router->dispatchToRoute()in Router.php line 511
at Router->dispatch()in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}()in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}()in Debugbar.php line 51
at Debugbar->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in TransformsRequest.php line 30
at TransformsRequest->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in TransformsRequest.php line 30
at TransformsRequest->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in ValidatePostSize.php line 27
at ValidatePostSize->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle()in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in Pipeline.php line 102
at Pipeline->then()in Kernel.php line 151
at Kernel->sendRequestThroughRouter()in Kernel.php line 116
at Kernel->handle()in index.php line 54
at {main}()in index.php

**Comment by hisorange** [comment]
This class ```use DeviceDetector\Parser\Client\Browser;``` is not in this package, this package using facades and you only have to ```use Browser;``` ^.^
