### ISSUE TITLE
Class 'Browser' not found  in laravel 5.3

### ISSUE THREAD

**Issue by meet0929** [hisorange/browser-detect#104]
I added providers and alias in config/app.php
'providers' => [
        // Package Service Providers...
        \hisorange\BrowserDetect\ServiceProvider::class,
    ]
 'aliases' => [
        'Browser' => \hisorange\BrowserDetect\Facade::class,
    ]
showing error in blade 
$result = \Browser::detect();
dd($result);

**Comment by hisorange** [comment]
Maybe empty your caches, the tests are covering all the supported versions.
Post a backtrace and we can look into it.
