### ISSUE TITLE
OS related is methods

### ISSUE THREAD

**Issue by Gummibeer** [hisorange/browser-detect#105]
Hey,

thanks for this great package. The only thing I miss are some of these `isXyz()` methods for the most common OS.
I would think about:
* `isApple()`
* `isWindows()`
* `isLinux()`
* `isAndroid()`

**Comment by hisorange** [comment]
Thanks for the feedback, will bundle it into the next update ^.^

**Comment by Gummibeer** [comment]
@hisorange will you still do this?
