### ISSUE TITLE
Laravel 6.0

### ISSUE THREAD

**Issue by arisdevx** [hisorange/browser-detect#111]
please support laravel 6

**Comment by pablofernandezgh** [comment]
Same issue here. Laravel 6.0 requires PHP >= 7.2
Browser-detect requires the extension mcrypt, which is not included in PHP 7.2 or 7.3

**Comment by SudoGetBeer** [comment]
I made a pull request #112 maybe this helps a little

**Comment by apoca** [comment]
Anyone knows if @SudoGetBeer pull request is working or when will be accepted?!

**Comment by therealahall** [comment]
FWIW, I took @SudoGetBeer's PR, forked this, and applied it which can be found here: https://github.com/aaron-hall-7/browser-detect. Once this repo gets updated, I'll go back to using it, but for now this is working for me.

**Comment by devsrv** [comment]
forked & added Laravel 6.0 support [devsrv/browser-detect](https://github.com/devsrv/browser-detect) 
use until the owner accepts #112 

- [how to install](https://github.com/devsrv/browser-detect#how-to-install)
- [how to use](https://github.com/devsrv/browser-detect#how-to-use)

**Comment by hisorange** [comment]
Merged, will release a new improved version this week ^.^
