### ISSUE TITLE
how it work for laraval 5.8.*

### ISSUE THREAD

**Issue by amarezenebe** [hisorange/browser-detect#115]
After I install i don't now how it work 
I flow the documentation 
I call Browser::isDesktop() FOR test but 
It return error call to undefined DeviceDetector\parser\Browser::isDesktop()
Also I try the blade also is not work
@@@@@@@@@@@@@@@@@@@@@@
IS THERE ANY things I HAVE TO SET UP OR DO BEFORE I USE IT

**Comment by amarezenebe** [comment]
The blade also is not work
Please help me

**Comment by amarezenebe** [comment]
is their any one ?????

**Comment by shaneru** [comment]
I am also testing this out. 

Did you call the facade?

if not. Try: "use hisorange\BrowserDetect\Facade as Browser;"

**Comment by doghap** [comment]
you can use like this : 
```
Browser::detect()->isMobile()
```
