### ISSUE TITLE
What about laptop

### ISSUE THREAD

**Issue by ccssmania** [hisorange/browser-detect#116]
First thank you so much for the package.
BTW, I need to know if is it possible to add a new detector it means currently there are desktop, tablet and mobile but I need add a laptop detector some thing as:
Desktop : 2560 x a1440 __ 1920 x 1080 ___ 1680 x 1050
Laptop : 1440 x 900
Tablet : 1024 x 768
mobile : < Tablet

**Comment by hisorange** [comment]
Sadly there is no way to detect resolution of any kind on PHP side. You need to run a client side detector for this.
You can trick the client with some clever CSS / image links to tell their resolution but this needs a lot of hack, and not reliable :D
