### ISSUE TITLE
osName is undefined on Ubuntu/Firefox / Browser v

### ISSUE THREAD

**Issue by crslp** [hisorange/browser-detect#128]
I hit the enter too early ... 

Using Browser ~3 on Laravel 5.8
Most of the methods are working as expected or return an empty string.

But, 
Browser::platformName()
fails:
Undefined property: hisorange\BrowserDetect\Result::$osName

The user-agent string on my machine is as follows:
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"

**Comment by crslp** [comment]
Nevermind, made a mistake and installed an older version.
Working fine now!

**Comment by hisorange** [comment]
Glad to hear it worked out ^.^
