### ISSUE TITLE
browscap ini pulling

### ISSUE THREAD

**Issue by goranata** [hisorange/browser-detect#13]
Tested with and without the plugin, cleared cache and tested in multiple browsers.

ErrorException
file_get_contents(http://browscap.org/stream?q=Full_PHP_BrowsCapINI): failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests (View: /***_/**_/app/views/home/index.blade.php)

**Comment by Lvm-Daud** [comment]
Hi,
I have set auto update on. How can I immediately update my .ini file.
Thanks
