### ISSUE TITLE
Facade and blade directives not working after install on laravel 5.8

### ISSUE THREAD

**Issue by pkkann** [hisorange/browser-detect#131]
Installed a completely fresh laravel 5.8 version.
Ran `composer require hisorange/browser-detect "^3"`

Afterwards the blade directives are just rendering as plain text, and the Browser facade is never found in any controller.

I know this package has been tested from here to the end, but i have tried several times, and it is just not working.

I have found several other issues regarding this, but they all got "stalled" with not response

**Comment by hisorange** [comment]
Hey there, the issue come out in real world usage and was fixed in the version 4 and afterwards but was never backported to 3.x.
