### ISSUE TITLE
4.2.0 `getUserAgentString()` typehint issue

### ISSUE THREAD

**Issue by matthewnessworthy** [hisorange/browser-detect#141]
https://github.com/hisorange/browser-detect/commit/c1c1a55a0c1bc4ae9c9e603cdcf6a9148ebcef4e#r37539567

`Return value of hisorange\BrowserDetect\Parser::getUserAgentString() must be of the type string, null returned`

**Comment by hisorange** [comment]
Thank You, fixed it!
