### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by xutongle** [hisorange/browser-detect#146]
`\hisorange\BrowserDetect\Parser::__construct` method 

```php
$this->config = array_merge_recursive(
            require(__DIR__ . '/../config/browser-detect.php'),
            $config
        );
```
If I use a custom configuration file, it will cause a configuration exception。
It will merge custom configuration and custom configuration, and the merged configuration is not expected.

log
```
[2020-03-05 16:57:29] production.ERROR: array (
  'cache' => 
  array (
    'interval' => 
    array (
      0 => 10080,
      1 => 86400,
    ),
    'prefix' => 
    array (
      0 => 'bd4_',
      1 => 'bd4_',
    ),
  ),
  'security' => 
  array (
    'max-header-length' => 
    array (
      0 => 2048,
      1 => 2048,
    ),
  ),
)  
```

**Comment by xutongle** [comment]
As a temporary workaround, do not use a custom configuration file.

**Comment by xutongle** [comment]
This bug is mainly due to the incorrect use of `array_merge_recursive`, resulting in the merged configuration file is not expected.

https://www.php.net/manual/en/function.array-merge-recursive.php 

Example 

```php
<?php
$ar1 = array("color" => array("favorite" => "red"), 5);
$ar2 = array(10, "color" => array("favorite" => "green", "blue"));
$result = array_merge_recursive($ar1, $ar2);
print_r($result);
?>
```
The above example will output:
```
Array
(
    [color] => Array
        (
            [favorite] => Array
                (
                    [0] => red
                    [1] => green
                )

            [0] => blue
        )

    [0] => 5
    [1] => 10
)
```

**Comment by hisorange** [comment]
Oh my, the PR will be merged today. My bad, I think I forgot how to PHP :D

**Comment by xutongle** [comment]
Good thank you, I hope to complete the integrity test and release a new version as soon as possible, otherwise it will affect the online environment of many systems.
