### ISSUE TITLE
Text-based web browser

### ISSUE THREAD

**Issue by streetclaw** [hisorange/browser-detect#151]
- Is there an easy way to detect if a text-based web browser is visiting the website like `isMobile()` for mobile devices?
- Are text-based web browser like Links, ELinks, Lynx, ... supported?

**Comment by hisorange** [comment]
No, saddly there is not too much development on this segment. As the package itself does not contain browser data, it cannot be supported if the underlyint libraries does not implement it.

Sorry, this feature will not be implemented. :/
