### ISSUE TITLE
Undefined class 'Browser' 

### ISSUE THREAD

**Issue by JieGenius** [hisorange/browser-detect#152]
Do I need to add Facade by myself?

//I think the browser-detect was installed successfully.
Using version ^4.2 for hisorange/browser-detect
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update

**Comment by JieGenius** [comment]
use Browsers is valid.   but phpStorm does not have code completion and remind me Undefined class 'Browser'

**Comment by ryahconstantino** [comment]
If someone want to remove that error, just use this:

`use hisorange\BrowserDetect\Facade as Browser;`

**Comment by hisorange** [comment]
I seen some tool long ago which generates code completion helpers for the laravel magic, or use the @ryahpalma solution to help the IDE figure out :)
