### ISSUE TITLE
Detect in-app browsers

### ISSUE THREAD

**Issue by juliomotol** [hisorange/browser-detect#156]
How to detect if a browser is in-app (via WebView)?

We were able to check for Facebook and Ig, by using `Browser::browserFamily()` but it will be hectic to check for all the apps that we  want to check.

It would be ideal if we could just do `Browser::isInApp`. Where it does something like [this](https://github.com/f2etw/detect-inapp/blob/master/src/inapp.js#L38-L47).

**Comment by hisorange** [comment]
Aye,

Sadly this library is feature locked, and I am only maintaining code bugs, but!

You provided the solution as well, extend the browser class and by using the linked regex you can test on the userAgent string to get the isInApp functionality ^.^

**Comment by juliomotol** [comment]
Oh I see, if that is the case I feel there is be a much better way to extend functionalities for this instead of having to directly extend the browser class. Like having it "macroable". Some thing much like [Laravel's `Collection::macro()`](https://laravel.com/docs/7.x/collections#extending-collections)

**Comment by hisorange** [comment]
Released in the latest 4.3 version. I know it's not a same day release but had some free time and added it into the library.

Thanks for the request, have a nice day!
