### ISSUE TITLE
[suggestion] Chromium-based Edge

### ISSUE THREAD

**Issue by futzlarson** [hisorange/browser-detect#157]
Would be cool to detect this, which is version 79+.

**Comment by futzlarson** [comment]
bump

**Comment by hisorange** [comment]
Hey there, as mentioned on the readme the package has no new development just bug fixes.
The version detection mentioned above comes from an included packages, the browser detect only bundles and regulates the output with some magic to get the best result, but does no actual string matching.

Sorry,
