### ISSUE TITLE
IPAD detection not working

### ISSUE THREAD

**Issue by RezaAb** [hisorange/browser-detect#158]
Hi. I found a problem in this package about detecting some of IPAD devices.
according to the below link, I found that the new devices have different User-Agent and Safari is sending the User-Agent of its macOS counterpart.
[https://developer.apple.com/forums/thread/119186](https://developer.apple.com/forums/thread/119186)

So in my codes for the IPAD devices, some methods not working like isTablet() or isMobile()

I can detect wit JS code like below but I couldn't resolve it with the User-Agent.

`const ua = window.navigator.userAgent.toLowerCase();`
`const isiPad = ua.indexOf('ipad') > -1 || ua.indexOf('macintosh') > -1 && 'ontouchend' in document;`

It would be great if we could somehow solve this issue for the IPAD devices.

**Comment by hisorange** [comment]
Hey there,

Sorry but the detection result coming from 3 different package where the actual pattern matching happens, the browser detect package only bundles those awesome packages and provides a user friendly and regulated output. So, to enhance detection this issue has to be raised in the included repositories like mobile detect, uaparser, or piwik detector.

Sorry for the long response, but this package is only maintaned for bug fixes.
