### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by incoming-th** [hisorange/browser-detect#164]
Hi,

Just to make sure this is working with Laravel 8 - it should in theory - as I see no issue, but better to have tests run and update the README once it is confirmed?

Thanks

**Comment by hisorange** [comment]
Hehe, thanks for the update, I didn't follow the laravel releases for a quite a time now, I will make sure to update the tests for laravel 8.

**Comment by hisorange** [comment]
The test are running for 2,5 hour now, I definitely have to replace the service now. But the build is available on the dev branch now, and when the run finished, gona merge to release tomorrow.

**Comment by hisorange** [comment]
Released in 4.4.0
