### ISSUE TITLE
Browser::parse(): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by futzlarson** [hisorange/browser-detect#165]
When doing `Browser::parse($agent)`

I sometimes get:

`file_put_contents(/var/www/html/hidden/storage/framework/cache/data/d8/ab/d8ab137e137fbf415d960746d1d2e63d409f2e20): failed to open stream: Permission denied`

Rarely, but it happened today. I know this would appear to be a permissions issue, but note the file exists and is world readable:

```
$ ls /var/www/html/hidden/storage/framework/cache/data/d8/ab/d8ab137e137fbf415d960746d1d2e63d409f2e20

-rw-r--r-- 1 www-data www-data 1.1K Feb  1 12:33 /var/www/html/hidden/storage/framework/cache/data/d8/ab/d8ab137e137fbf415d960746d1d2e63d409f2e20
```

Any ideas? Using 4.2.2

**Comment by hisorange** [comment]
Aye,

The package uses the Laravel's ```Illuminate\Cache\CacheManager``` class, so this issue derives from there.
Some years ago I tested the WSL 1.x and I often ran into similar issues, maybe you experiencing the same?

**Comment by futzlarson** [comment]
Not sure what WSL is or what the proposed solution is? I'm on 7.25 for this project.

**Comment by PoOwAa** [comment]
@futzlarson WSL is `Windows Subsystem for Linux`, if you're a Windows user you can run a GNU/Linux environment directly on Windows unmodified, without the overhead of a virtual machine / dualboot setup.

Can you describe your environment? OS, PHP version, Laravel version etc. to get a more accurate perspective what is going on.

**Comment by futzlarson** [comment]
To be clear, I am not a contributor to this project, I only use it, so I have no idea what you're referring to with WSL. I'm trying to parse a user agent string and know nothing about how the internals of this package does it.

OS: Ubuntu 18.04
PHP: 7.3.24
Laravel: 7.25

**Comment by hisorange** [comment]
It's weird, never seen this on linux, anyways there is multiple thing about this, one it gets permission denied on write, but then the file exists so it worked :D

Two the issue is in the laravel repository, the cache manager which causes the error is a laravel package https://github.com/illuminate/cache

**Comment by hisorange** [comment]
To be exact this line causes the error:
 https://github.com/illuminate/filesystem/blob/master/Filesystem.php#L185

**Comment by futzlarson** [comment]
Gotcha. Seems like it may be solved by upgrading Laravel so I'll do that.
