### ISSUE TITLE
Detecting Brave Browser

### ISSUE THREAD

**Issue by xGwein** [hisorange/browser-detect#166]
Hi, is there a way to detect user that using Brave browser?

Because I'm using it, and when testing with isChrome(), the result return true

Thanks in advance

**Comment by hisorange** [comment]
We can implement a simple regex test on it, until you can do a /Brave/i match on the user agent fetched from the result smth like this.

```php
if ($r->isChrome() && preg_match("/Brave/i", $r->userAgent())) {
 echo "It's brave!";
}

```

**Comment by xGwein** [comment]
Hi, thanks for the reply

Unfortunartely, I don't see any 'Brave' character in my UA

This is my UA

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36`

**Comment by hisorange** [comment]
That is a problem, because it seems to be on purpose, to cover the user agent and mislead the tracking scripts.

I can provide a weak detection based on https://developers.whatismybrowser.com/useragents/explore/software_name/brave/ lists like this. But when a browser wants to hide it's identity then nothing left to do.

**Comment by hisorange** [comment]
We will add this feature in 4.4.1

**Comment by PoOwAa** [comment]
@xGwein I just checked Brave browser on my computer and got the following result:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/88.0.4324.192 Safari/537.36`

It's the same behaviour (Brave Chrome) like the useragent samples mentioned by @hisorange 

If you still facing this super secret UA, can you please check in your browser console what is the result of the following commands?

`navigator.brave` and `navigator.brave.isBrave()`

```
> navigator.brave
Brave {}
__proto__: Brave

> navigator.brave.isBrave()
Promise {<fulfilled>: true}
__proto__: Promise
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: true
```

If that works, then you can check only on client side.
