### ISSUE TITLE
Move from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by PoOwAa** [hisorange/browser-detect#167]
As Travis announced last year, travis-ci.org is deprecated from December 31st, 2020. The [newsletter](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom) said it should be completely closed down since that, but fortunately, they still maintain it for a couple of weeks.

If you open travis-ci.org you can face the warning on the top of the site:
`Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.`

According to these, the project should move to travis-ci.com (or use github actions, but it's more effort), before the auto migration to avoid errors.

Migration documentation is available [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

**Comment by hisorange** [comment]
Released in 4.4.0
