### ISSUE TITLE
Device Model Version

### ISSUE THREAD

**Issue by robertmylne** [hisorange/browser-detect#172]
I read your info and you did say you weren't updating this package anymore, but I thought what would really be good under `Browser::deviceModel()` would be to also see what version it was, for instance `iPhone 11` and not just `iPhone`.

**Comment by PoOwAa** [comment]
I just checked the UA on my phone and got the following result:
`Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

Result on my Macbook with safari-->develop-->user agent-->iphone
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1`

As you can see there is no difference between those (only iOS version).

Moreover browser-detect uses [matomo/device-detector](https://github.com/matomo-org/device-detector) to determine the model. Maybe you can ask them to find out how to detect version as well! :)

**Comment by hisorange** [comment]
Yep, saddly the iPhones not sending their version in the user agent string, so we cannot determine any more information about the visitor.
