### ISSUE TITLE
Support for Chromium

### ISSUE THREAD

**Issue by kaiserkiwi** [hisorange/browser-detect#173]
Hello there,

I was wondering if it would be possible to add Chromium support. Browsers like Edge, Chrome or Vivaldi all run with Chromium and therefore render everything pretty much identically. It would make queries much easier if I didn't have to check for Edge, Vivaldi, Brave, Opera, etc. and their respective version numbers. (The Version of Edge is identically with Chromium, but Vivaldi has it's own versioning)

So is it possible to add support for an `isChromium()` method plus Chromium version number?

**Comment by hisorange** [comment]
Yep, sounds useful!

I will do the planning for it in the next days.
