### ISSUE TITLE
Parse passed useragent

### ISSUE THREAD

**Issue by Nevermind23** [hisorange/browser-detect#175]
I plan to use useragent on queued job, so that I am unable to use default isBot or browserFamily or any other functionality, is it possible to pass useragent manually to be able to parse it ?
Or is there any other way to process browser/platform data in queued job?

Thank you

**Comment by hisorange** [comment]
Yo.

Yes, it is https://github.com/hisorange/browser-detect#advanced-usage-information, simply call the Browser::parse with the UA :)
