### ISSUE TITLE
Browser version ending up being 0

### ISSUE THREAD

**Issue by marktopper** [hisorange/browser-detect#18]
I get the following result using Chrome:

```
isMobile: false,
isTablet: false,
isDesktop: true,
isBot: false,
browserFamily: "Chrome",
browserVersionMajor: 0,
browserVersionMinor: 0,
browserVersionPatch: 0,
osFamily: "MacOSX",
osVersionMajor: 0,
osVersionMinor: 0,
osVersionPatch: 0,
deviceFamily: "",
deviceModel: "",
mobileGrade: "",
cssVersion: 1,
javaScriptSupport: true
```

and in Safari

```
isMobile: false,
isTablet :false,
isDesktop:true,
isBot: false,
browserFamily: Safari,
browserVersionMajor: 0,
browserVersionMinor: 0,
browserVersionPatch: 0,
osFamily: MacOSX,
osVersionMajor: 0,
osVersionMinor: 0,
osVersionPatch: 0,
deviceFamily: "",
deviceModel: "",
mobileGrade: "",
cssVersion: 1,
javaScriptSupport: true
```

Can this bug be fixed somehow or am I the only one getting it?

**Comment by Ahmed-90** [comment]
Facing the same problem even with "UserAgentStringApi" enabled

User agent:
Chrome:

```Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36```

Firefox:

```Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0```

**Comment by mikebronner** [comment]
Getting 0 for all versions (browser and os), even with UserAgentStringAPI enabled.

My UserAgent string: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.5 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.5`
