### ISSUE TITLE
Windows 11 is being detected as Windows 10

### ISSUE THREAD

**Issue by p431i7o** [hisorange/browser-detect#182]
According to Microsoft documentation https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11 
they share the same base as Windows 10
the way to differentiate them is reading the User-Agent Client Hints 
the flag Sec-CH-UA-Platform-Version values between 1.0.0 and 10.0.0 indicates Windows 10
values at 13.0.0  and above are from Windows 11 

Browsers that send this information are Ms Edge, Chrome 95+ and Opera

In the example provide from Microsoft this would be how to detect the difference (js code)
```
navigator.userAgentData.getHighEntropyValues(["platformVersion"])
 .then(ua => {
   if (navigator.userAgentData.platform === "Windows") {
     const majorPlatformVersion = parseInt(ua.platformVersion.split('.')[0]);
     if (majorPlatformVersion >= 13) {
       console.log("Windows 11 or later");
      }
      else if (majorPlatformVersion > 0) {
        console.log("Windows 10");
      }
      else {
        console.log("Before Windows 10");
      }
   }
   else {
     console.log("Not running on Windows");
   }
 });
```

**Comment by hisorange** [comment]
Thanks @p431i7o gona implement it today.
Awesome detailed instructions ^.^

**Comment by hisorange** [comment]
Hmm, sadly this will not work for the lib.
The code and the explanation requires the "Sec-CH-UA" header and the library only accesses the "User-Agent" header.

Which means without the extra information we cannot determine the platform version reliably. In the documentation the reference to Win11 is parsed from the extra header.

Sorry we cannot implement this, but as an alternative it is possible to simply check for the secondary header when the BD indicates a windows platform.

Maybe in the future we will extend the request processing capabilities, even tho if that's the case then we cannot operate from logs and other simple UA sources any more :/
