### ISSUE TITLE
isInApp returns true with Android Chrome Browser 102.0.5005.78

### ISSUE THREAD

**Issue by tcgunel** [hisorange/browser-detect#185]
Below android chrome user agent is returning true with the isInApp regexp.

Mozilla/5.0 (Linux; Android 12; ONEPLUS A6000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36

To fix my issue, I had to use if $_SERVER['HTTP_X_REQUESTED_WITH'] is set.

**Comment by hisorange** [comment]
Sadly this is not a clear cut. After digging into the topic, the inApp for android is just a good guess nothing else, as the implementation changing version to version.

I have added multiple new detector refinements and tests, but that's the best we can do for now.
