### ISSUE TITLE
Detect TWA or PWA request

### ISSUE THREAD

**Issue by kilicabdulkadir** [hisorange/browser-detect#192]
Can we detect requests opened via TWA (Trusted Web Application) through this package?

**Comment by hisorange** [comment]
At first glance I don't think we can. As this package only works with the HTTP requests made toward the server and processes the User-Agent header, any client side behaviour should be detected on the client.

TWA should make no difference in the application's backend code.
But let me know if this is reflected somewhere in the UA.

**Comment by kilicabdulkadir** [comment]
Sometimes application markets can remove the application from the market because there are payment screens on the sites. There may be a need to convert the website to PWA and publish them in application markets (TWA). In order to prevent the application from being removed from the markets, phrases such as "Please continue on the website" are written where the payment sections are. Wouldn't that be useful for controlling it ?

**Comment by hisorange** [comment]
Oh I think there is a misunderstanding. This package only works from the HTTP request's User Agent header.
From my readings, the TWA makes no difference for this header.

Your use case seems to be a 100% client side. ^.^
