### ISSUE TITLE
OS version detects Browser Version

### ISSUE THREAD

**Issue by marktopper** [hisorange/browser-detect#20]
Here is a dump of the return of `detect`-method, but added a `user-agent` value to the array so you can see it all.

It says that OS version is 38.0.2125, but this is the Chrome version, not the OS version.

```
object(hisorange\BrowserDetect\Result)[330]
  protected 'attributes' => 
    array (size=18)
      'isMobile' => boolean false
      'isTablet' => boolean false
      'isDesktop' => boolean true
      'isBot' => boolean false
      'browserFamily' => string 'Chrome' (length=6)
      'browserVersionMajor' => int 38
      'browserVersionMinor' => int 0
      'browserVersionPatch' => int 2125
      'osFamily' => string 'OS X' (length=4)
      'osVersionMajor' => int 38
      'osVersionMinor' => int 0
      'osVersionPatch' => int 2125
      'deviceFamily' => string '' (length=0)
      'deviceModel' => string '' (length=0)
      'mobileGrade' => string '' (length=0)
      'cssVersion' => int 1
      'javaScriptSupport' => boolean true
      'user-agent' => string 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36' (length=121)
```

**Comment by ArtbyArjan** [comment]
Unfortunatly, this doesn't seem to solve the problem where an iPad is detected as mobile.
In fact, a Windows Surface tablet and a Samsung Galaxy Tab 3 are also still detected as mobile.

I have installed UAParser, uncommented line 79, 85 and 86 in plugins.php (enabling UAParser), uncommented line 110 in plugins.php and moved line 104 - 110 to line 75 (above the UAParser section) but it still doesn't work.
Did I forget something?

**Comment by marktopper** [comment]
I had the same problem @ArtbyArjan.
Just thought I was the one making something wrong.

**Comment by hisorange** [comment]
The problem deeply connected to the MobileDetect library, they identify tablets as both mobile and tablet in the same time, need to make an update on their plugin controller. 

Unfortunately for now I have no time for this project, if any1 makes a PR i ran a test and pull it but can't do no more.

**Comment by hisorange** [comment]
@ArtbyArjan @marktopper in any case did any of you flushed the cache or turned it out, I just ran the test again from a clean install and it working fine for me, so maybe you still getting the cached result?
