### ISSUE TITLE
Class "Spyc" not found error

### ISSUE THREAD

**Issue by tanero** [hisorange/browser-detect#217]
When I wanto call Browser facade methods, I get the below error. 

![image](https://github.com/hisorange/browser-detect/assets/3600684/bd23ba39-e411-43a6-a689-78066a8c31c1)

**Comment by pixelplant** [comment]
Can confirm this on version 5.0.3 running on php 8.2. We get the same error, it worked just fine before upgrading to PHP 8.2 (from PHP 8.1)

The error happens in our views, wherever the code ```Browser::isDesktop()``` is called, for example

**Comment by pixelplant** [comment]
might be linked to this recent issue: https://github.com/mustangostang/spyc/issues/90

**Comment by pixelplant** [comment]
seems to have been linked to the retag issue on the above package. after a retry it works now

**Comment by artem-schander** [comment]
@pixelplant 
what do you mean with "after a retry"
I have the same issue but a retry does not help. also `composer du` does not help either

**Comment by ramyelsabahy** [comment]
The same here , laravel 9 & php 8.1
Did you find a solution ?

**Comment by roborourke** [comment]
This was a packagist issue that has now been resolved.

**Comment by pixelplant** [comment]
> @pixelplant what do you mean with "after a retry" I have the same issue but a retry does not help. also `composer du` does not help either

Sorry I wasn't clear about it, by retry I meant removing the composer.lock and the vendor folder and just doing another composer install. It seems they retagged the latest version of mustangostang/spyc package and that fixed the issue

**Comment by tanero** [comment]
This problem seems to be fixed for now. After the composer update process, a new package was installed from the packagist repo and the library started to work without any problem.
