### ISSUE TITLE
ReflectionException: Class browser-detect.parser does not exist

### ISSUE THREAD

**Issue by Cardy** [hisorange/browser-detect#29]
Hi,
I'm using Laravel 4.2 and after installing your package I've got an error id if I use any BrowserDetect method, I receive the following error: ReflectionException Class browser-detect.parser does not exist
Do you have any hint on how to resolve this problem?
Thanks

**Comment by hisorange** [comment]
I belive you use the wrong version, 1.0.4 is for laravel 4, the newest 2.0.0 version is an L5 update.

**Comment by masterjus** [comment]
I have the same problem

**Comment by Cardy** [comment]
@hisorange I use 1.0.4 because I'm on Laravel 4.2.

**Comment by MoseyM** [comment]
Installed v2 for l5 using l5.0 and getting error that class doesn't exist. using BrowserDetect...what else needs to be done for this to work??
