### ISSUE TITLE
Issues with publish config files

### ISSUE THREAD

**Issue by libern** [hisorange/browser-detect#31]
php artisan vendor:publish
Copied File [/vendor/hisorange/browser-detect/src/config/config.php] To [/config/hisorange/browser-detect/browser-detect-config.php]
Copied File [/vendor/hisorange/browser-detect/src/config/plugins.php] To [/config/hisorange/browser-detect/browser-detect-plugins.php]
Publishing Complete!
==================

This generates config files under "/config/hisorange/browser-detect/" folder where you use /config/ folder ...
Hopes you can resolve the issue.

**Comment by hisorange** [comment]
The v2.0.1 should fix this, please pull it down and let me know if it's working or not. Thanks for the notice.

**Comment by masasron** [comment]
Here is my quick fix.

File:`vendor/hisorange/browser-detect/src/Parser.php`

BEFORE
```PHP
public function __construct(Application $app)
	{
		// Store the application.
		$this->app 		= $app;

		// Import the package configuration to the parser object.
		$this->objectConfigImport(config('browser-detect-config'));

		// Import the plugins.
		$this->pluginCollectionImport(config('browser-detect-plugins'));
	}
```

AFTER
```PHP
public function __construct(Application $app)
    {
        // Store the application.
        $this->app = $app;

        // Import the package configuration to the parser object.
        $this->objectConfigImport(config('hisorange.browser-detect.browser-detect-config'));

        // Import the plugins.
        $this->pluginCollectionImport(config('hisorange.browser-detect.browser-detect-plugins'));
    }
```

**Comment by libern** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing hisorange/browser-detect (2.0.0)
  - Installing hisorange/browser-detect (dev-master 695672f)
    Downloading: 100%         

Writing lock file
Generating autoload files
Exception: Argument 1 passed to hisorange\BrowserDetect\Parser::objectConfigImport() must be of the type array, null given, called in /Users/Libern/PHP/www/vendor/hisorange/browser-detect/src/Parser.php on line 77 and defined
Skipping \hisorange\BrowserDetect\Facade\Parser.

----------

It has an exception while update this package.
