### ISSUE TITLE
Error in ObjectConfig.php: Argument must be array, null given

### ISSUE THREAD

**Issue by djtechonline** [hisorange/browser-detect#32]
Great script, but I suddenly have trouble getting this package to work properly on Laravel 5.  Here is the error thrown:

"ErrorException in /var/www/test-site/vendor/hisorange/traits/src/ObjectConfig.php line 70:
Argument 1 passed to hisorange\BrowserDetect\Parser::objectConfigImport() must be of the type array, null given, called in /var/www/test-site/vendor/hisorange/browser-detect/src/Parser.php on line 77 and defined (View: /var/www/test-site/resources/views/site/index.blade.php)"

The line causing the error on my index page is as follows:
<?php echo BrowserDetect::browserName(); ?>

My config\app.php is setup properly for both providers and aliases.  I have even tried removing and then re-installing ~2.0 with composer, but I still get the error.   

I'm not sure what is wrong.  Any ideas or suggestions would be of great help.  Any thoughts?

**Comment by hisorange** [comment]
Newest PR should solve the issue please pull down the v2.0.1.

**Comment by djtechonline** [comment]
Problem looks to be corrected with those 2 small changes. Thank you!

**Comment by threeel** [comment]
i am having the same exact issue on 2.0.2 

ErrorException in ObjectConfig.php line 70:
Argument 1 passed to hisorange\BrowserDetect\Parser::objectConfigImport() must be of the type array, null given, called in /var/www/vendor/hisorange/browser-detect/src/Parser.php on line 77 and defined

**Comment by GaurangGhinaiya** [comment]
i am having too the same exact issue on 2.0.2

**Comment by ngugijames** [comment]
@GaurangGhinaiya I solved this by simply running `php artisan vendor:publish` to publish the packages config files

**Comment by mikebronner** [comment]
Having this issue as well. Would prefer if it could default to load config from package, and not rely on it being published. Should only need to publish if I want to make changes to the config.
