### ISSUE TITLE
Error after composer update

### ISSUE THREAD

**Issue by goranata** [hisorange/browser-detect#33]
Hi, I've just update through the composer and I got the current error:

Argument 1 passed to hisorange\BrowserDetect\Parser::objectConfigImport() must be of the type array, null given, called in C:\xampp\htdocs\greekhotelsapi\vendor\hisorange\browser-detect\src\Parser.php on line 77 and defined (View: C:\xampp\htdocs\greekhotelsapi\resources\views\homepage.blade.php)

I'm only using these examples: BrowserDetect::isTablet(), BrowserDetect::isDesktop(), BrowserDetect::isMobile(), and everything seemed to be working just fine before.

Could you please advice?

**Comment by opheliadesign** [comment]
Experiencing the same error here..

**Comment by goranata** [comment]
Hi, the answer is here:
https://github.com/hisorange/browser-detect/issues/31

This has helped my case.

**Comment by opheliadesign** [comment]
I installed the package and forgot to run the vendor publish. Did that and still receiving the error. I installed for the first time this morning.. suggestions?

**Comment by barkersinternet** [comment]
Hi,

You can fix this by moving the 2 config files into the config directory

browser-detect-config.php
browser-detect-plugins.php

Matt

**Comment by olivierneo** [comment]
The Matt's solution works fine, thanks !
