### ISSUE TITLE
Minor update to ReadMe

### ISSUE THREAD

**Issue by kirikintha** [hisorange/browser-detect#35]
Hi there,

Was checking out your module on Laravel 4.2 and noticed that in your current read me you are using the artisan command for laravel 5.

I looked through your commits and found:

php artisan config:publish hisorange/browser-detect - for Laravel 4

Since you include version 1.\* instructions, the above command works properly! Minor update. Thanks!

**Comment by hisorange** [comment]
#76 

Thanks!
