### ISSUE TITLE
Support for new Microsoft Edge browser in Windows 10?

### ISSUE THREAD

**Issue by djtechonline** [hisorange/browser-detect#36]
I am running a preview of Windows 10 and I noticed that the new Microsoft Edge browser is not detected.  Will support be added soon?

**Comment by troiano86** [comment]
this would be a good thing... want this

**Comment by hisorange** [comment]
Trident detection is now supported by calling the function like

```php
BrowserDetect::result()->isIE(true);
```

This will include the Trident into the matching.
It was not added originally because the Trident is not a traditional IE update.

**Comment by futzlarson** [comment]
For anyone else looking for this, until proper support is added, you can achieve it with this:

`@if (str_contains(Browser::browserEngine(), 'Edge')`
