### ISSUE TITLE
Not able to find the windows phone

### ISSUE THREAD

**Issue by haricet** [hisorange/browser-detect#39]
Hi ,
    I am happy to follow the well builded  code.thak you so much guys.you done a good job.i have to know this will work for windows phone?, and how can i do that.i am really new to laravel.i tried by windows phone.but it shows same android os.can u please help me.thak you so much.

**Comment by hisorange** [comment]
It should not show android if it's on windows but if you provide a user-agent and a result dump I can look into it.
