### ISSUE TITLE
It is to check the size and screen orientation?

### ISSUE THREAD

**Issue by quinhone** [hisorange/browser-detect#40]
example:
if (BrowserDetect::isMobile() and BrowserDetect::isMobile('display-width')> 500px) {
...
}
or
if (BrowserDetect::isTablet() and BrowserDetect::isTablet('horizontal')) {
...
}

**Comment by hisorange** [comment]
It's not possible to detect screen orientation on server side without a client side script.

If you wana detect screen orientation write a simple javascript which takes the document.windowWidth and document.windowHeight attributes and push it into a cookie this way you can pass the info on request to the server.

But you still can't detect a rotation by pure server side everything what happens after the php buffer is pushed is only client side.
