### ISSUE TITLE
info not compatible with L5

### ISSUE THREAD

**Issue by webeks** [hisorange/browser-detect#42]
providers =>         hisorange\BrowserDetect\Provider\BrowserDetectService::class

**Comment by rcaf** [comment]
What version of laravel are you using?

I installed browser-detect with laravel 5.1.27, and everything is working ok.

**Comment by webeks** [comment]
Laravel Framework version 5.1.26 (LTS)
clean install on ubuntu with PHP 5.5.30 (cli) (built: Oct 23 2015 17:21:45) 

I got it to work but spent some time digging around since your install info is out of date. providers in L5 seem to be registered a bit differently.

**Comment by hisorange** [comment]
"L5 support" wasn't more than a random PR I accepted, sadly I have 0 time to work with this project atm, and L5 didn't met my expectations, so in work I still use L4.

Sorry for the inconvenient, but without a doced PR I am not going to update the readme any further.
If you found a mistake please fork it and push PR with the reasoning so others will don't have to do the same, thanks!

**Comment by hisorange** [comment]
#76
