### ISSUE TITLE
Local use

### ISSUE THREAD

**Issue by Mastok1979** [hisorange/browser-detect#43]
Is it normal that i always have default results on my local application?

**Comment by rcaf** [comment]
In my local copy of my application, I get almost all data, but the data version (major, minor, patch) are always zero.

**Comment by Mastok1979** [comment]
hm! i dont have ip, browser ....

**Comment by hisorange** [comment]
If you use L4.* then it has to work perfectly fine, if it isn't then check your permissions maybe the cache file is not readable? or look up the log.

**Comment by Mastok1979** [comment]
no this is with laravel 5.1

**Comment by hisorange** [comment]
send in a dump please.
```php
var_dump($SERVER, YourBrowserDetectAlias::detect());
```

**Comment by Mastok1979** [comment]
what is the Server variale?

**Comment by Mastok1979** [comment]
object(hisorange\BrowserDetect\Result)#273 (1) { ["attributes":protected]=> array(17) { ["isMobile"]=> bool(false) ["isTablet"]=> bool(false) ["isDesktop"]=> bool(true) ["isBot"]=> bool(false) ["browserFamily"]=> string(25) "HiSoRange Generic Browser" ["browserVersionMajor"]=> int(0) ["browserVersionMinor"]=> int(0) ["browserVersionPatch"]=> int(0) ["osFamily"]=> string(20) "HiSoRange Generic OS" ["osVersionMajor"]=> int(0) ["osVersionMinor"]=> int(0) ["osVersionPatch"]=> int(0) ["deviceFamily"]=> string(0) "" ["deviceModel"]=> string(0) "" ["mobileGrade"]=> string(0) "" ["cssVersion"]=> int(0) ["javaScriptSupport"]=> bool(true) } }

**Comment by hisorange** [comment]
Sorry meant $_SERVER, wrote at night.

**Comment by hisorange** [comment]
Btw seems like the plugin does not getting the $_SERVER['HTTP_USER_AGENT'] string so try with

```php
var_dump(YourBrowserDetect::detect($_SERVER['HTTP_USER_AGENT']);
```

**Comment by Mastok1979** [comment]
<div class="col-sm-6">
			<div class="panel panel-primary">
	  			<div class="panel-heading">
	  				{{trans('news.news')}}
	  			</div>
				<div class="panel-body">
					<div class='container-fluid'>
						{{var_dump(BrowserDetect::detect($_SERVER['HTTP_USER_AGENT']))}}
					</div>
				</div>
			</div>
		</div>

its the same result:
object(hisorange\BrowserDetect\Result)#272 (1) { ["attributes":protected]=> array(17) { ["isMobile"]=> bool(false) ["isTablet"]=> bool(false) ["isDesktop"]=> bool(true) ["isBot"]=> bool(false) ["browserFamily"]=> string(25) "HiSoRange Generic Browser" ["browserVersionMajor"]=> int(0) ["browserVersionMinor"]=> int(0) ["browserVersionPatch"]=> int(0) ["osFamily"]=> string(20) "HiSoRange Generic OS" ["osVersionMajor"]=> int(0) ["osVersionMinor"]=> int(0) ["osVersionPatch"]=> int(0) ["deviceFamily"]=> string(0) "" ["deviceModel"]=> string(0) "" ["mobileGrade"]=> string(0) "" ["cssVersion"]=> int(0) ["javaScriptSupport"]=> bool(true) } }

**Comment by hisorange** [comment]
The "Generic Browser" is a replacment string for cases when the $_SERVER['HTTP_USER_AGENT'] is missing, so from this I guess you calling this through php built in server where the field is empty, if not then look into your environment cuz thats a generic header.

**Comment by Mastok1979** [comment]
i searched but i dont know what i have to do! can you help me?

**Comment by hisorange** [comment]
Please do this dump, with this I can see if it's your server config or your app setup is wrong.

```php
file_put_contents('dump.txt', json_encode($_SERVER, BrowserDetect::detect(), config(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
```

After you call this attach the dump.txt in your next comment here.

**Comment by Mastok1979** [comment]
json_encode() expects at most 3 parameters, 4 given (View: C:\Users\lango\Desktop\fifapic\fifapic\resources\views\front\index.blade.php)

i'll try to fix it but i dont know what your parameters do

**Comment by Mastok1979** [comment]
I did it in 3 lines and 3 files
Here the files:
[dump1.txt](https://github.com/hisorange/browser-detect/files/72424/dump1.txt)
[dump2.txt](https://github.com/hisorange/browser-detect/files/72425/dump2.txt)
[dump.txt](https://github.com/hisorange/browser-detect/files/72426/dump.txt)

**Comment by hisorange** [comment]
Uhm sorry I should stop writing code at 4am XD Wanted to dump all the var at once with an array

```php
file_put_contents('dump.txt', json_encode(array($_SERVER, BrowserDetect::detect(), config()), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
``` 
like this, but it's good as you sent it.
***

So, what I can see is a weird dump: you using a normal dev server not a built in and the $_SERVER contains the UA string, also you are on windows so it can't be permission problem; Which means everything should work correctly but seems like the BD not even running a single plugin.
***
I have just pushed a new commit to the dev-master which will check if there is any problem with your plugin configuration and will throw an InvalidPluginListException. Please pull the newest version and tell me if you getting this error or not.

**Comment by Mastok1979** [comment]
OK i will try it after Sauna :P ! Thanks

**Comment by Mastok1979** [comment]
i removed the package and did a new download (i dont know another solution for force an update)
here the dump.txt but it seems to be the same.
[dump.txt](https://github.com/hisorange/browser-detect/files/72704/dump.txt)

**Comment by hisorange** [comment]
To update to the current dev-master change your composer.json to 

```json
{
    "require": {
        "// other packages... this is just an example"
        "hisoranger/browser-detect": "dev-master"
    }
}
```

then run this.

```
composer update
```

This will pull the current dev-master branch.

**Comment by Mastok1979** [comment]
i'm an idiot! :D 
i saw it now and wanted to change my post. sorry.

[dump.txt](https://github.com/hisorange/browser-detect/files/72785/dump.txt)

**Comment by hisorange** [comment]
Hmm this is getting problematic since my last guess was that your plugin setup isn't loading but with the current dev-master that is not possible to go through without any plugin. 

Is this happening when you test is with other browsers like an old IE too? 
Because maybe that you didn't activated the cache update and you still using the 2 year old cache in the pack?
There is a cache/Browscap folder in the plugin empty it please.

**Comment by hisorange** [comment]
#76
