### ISSUE TITLE
Ipad Version

### ISSUE THREAD

**Issue by ghost** [hisorange/browser-detect#46]
Hi,

I'm testing the tablet detection with BrowserDetect::detect() and BrowserDetect::isTablet(). When I use desktop version or mobile, it's work, but if I used iPad, dosen't work, BrowserDetect::isTablet() return false.

I try with iPad 2. I am doing something wrong?

Regards!

**Comment by hisorange** [comment]
Aye, the main seems to be the browscap not loading the required browscap.ini and sadly I got not time to figure out why, sorry :/

**Comment by hisorange** [comment]
#76
