### ISSUE TITLE
Not working with native apps.

### ISSUE THREAD

**Issue by GaurangGhinaiya** [hisorange/browser-detect#48]
Hello.
I am using this as API in my application. 

```
$agent = BrowserDetect::detect();
return Response()->json(ResponseManager::getResult($agent, 10, ''));
```

Everything working fine but when i try to call using android native app then this would return wrong result. So is there any possibilities to how to get accurate result with native apps.

Thanks

**Comment by hisorange** [comment]
Use parse function with passed header value. #76
