### ISSUE TITLE
Windows 10 wrong detection

### ISSUE THREAD

**Issue by jesstine** [hisorange/browser-detect#51]
Hi,

I've tested BrowserDetect::browserFamily() using Chrome browser in Windows 7 and it returns Chrome which is correct. However in Windows 10 it returns Hisorange Generic Browser. Is there any solution to this that I can do on my side?

Thanks.

**Comment by omkarok2390** [comment]
@jesstine I have same problem. i have search a lot but still not getting any solution.  :(

**Comment by hisorange** [comment]
#76
