### ISSUE TITLE
Not Working on L 5.2

### ISSUE THREAD

**Issue by kamrava** [hisorange/browser-detect#54]
I've used this command :
`$result = \BrowserDetect::isMobile();
`
but it returns :
`Class 'BrowserDetect' not found`

Here is my app.php :
providers' => [
      hisorange\BrowserDetect\Provider\BrowserDetectService::class,
]

And Alias is :
aliases' => [
      'BrowserDetect' => hisorange\BrowserDetect\Facade\Parser::class,
]

Any ideas?

**Comment by artisaninweb** [comment]
Did you use the `BrowserDetect` in your controller?

**Comment by erfansahaf** [comment]
I've same problem!
Also IDE can't detect class methods.

**Comment by kamrava** [comment]
> Did you use the BrowserDetect facade in your controller?
Yes.

**Comment by robcaa** [comment]
Same problem! L 5.2
Class 'BrowserDetect' not found

**Comment by robcaa** [comment]
`composer update --no-scripts && composer update`
not helped :(

**Comment by BrandonLegault** [comment]
Same problem.

**Comment by hisorange** [comment]
#76
