### ISSUE TITLE
Not working on lumen 5.2

### ISSUE THREAD

**Issue by devat2s** [hisorange/browser-detect#55]
I've used this  :
`$result = \BrowserDetect::detect();` & tried `$result = BrowserDetect::detect();`
but it returns :

`Argument 1 passed to hisorange\BrowserDetect\Parser::__construct() must be an instance of Illuminate\Foundation\Application, instance of Laravel\Lumen\Application given, called in /home/vagrant/t2s-api/vendor/hisorange/browser-detect/src/Provider/BrowserDetectService.php on line 49 and defined`

Here is the 4 list I have followed

app.php :
`1. $app->register(hisorange\BrowserDetect\Provider\BrowserDetectService::class);`
`2. class_alias('hisorange\BrowserDetect\Facade\Parser', 'BrowserDetect');`

Composer
`3. {
    "require": {
        "hisorange/browser-detect": "2.*"        
    }
}`

& Artisan
`4. php artisan vendor:publish`

**Comment by vrga** [comment]
The answer should be kind of obvious: 
>  instance of Laravel\Lumen\Application given

If you moved your project from lumen to laravel, check that you dont have stuff cached,.
