### ISSUE TITLE
Remove version from composer.json

### ISSUE THREAD

**Issue by vrga** [hisorange/browser-detect#56]
You should not have the version bit in composer.json, because Packagist will not pick up newer releases, since the composer.json is stuck at 2.0.2

as an added bonus when you tag new releases in git, they should automatically be picked up by packagist, no further intervention needed.

**Comment by hisorange** [comment]
Thanks for the bit, will definitly use at the next update.

**Comment by jcoetsie** [comment]
Hi this is still in effect.
Your 2.0.4 tag has in its composer.json 2.0.2

Composer will not update and is stuck at 2.0.2

**Comment by hisorange** [comment]
#76
