### ISSUE TITLE
Detect Lumia

### ISSUE THREAD

**Issue by war20k** [hisorange/browser-detect#57]
`Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 630 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537`
-     "isMobile" => true
-     "isTablet" => false
-     "isDesktop" => false
-     "isBot" => false
-     "browserFamily" => "Internet Explorer"
-     "browserVersionMajor" => 0
-     "browserVersionMinor" => 0
-     "browserVersionPatch" => 0
-     "osFamily" => "AndroidOS"
-     "osVersionMajor" => 0
-     "osVersionMinor" => 0
-     "osVersionPatch" => 0
-     "deviceFamily" => "Nokia"
-     "deviceModel" => "iPhone"
-     "mobileGrade" => "A"
-     "cssVersion" => 0
-     "javaScriptSupport" => true

**Comment by hisorange** [comment]
#76
