### ISSUE TITLE
Only see "HiSoRange Generic Browser" - Laravel 5.3

### ISSUE THREAD

**Issue by elasticsteve** [hisorange/browser-detect#58]
Hi

I've tried to make this work for a few hours now with no success...

Followed your instructions.
` hisorange\BrowserDetect\Provider\BrowserDetectService::class,`
and
`'BrowserDetect' => hisorange\BrowserDetect\Facade\Parser::class,`

in app.php

but 
```
 $result = \BrowserDetect::detect();
        dd($result);
```
shows me only
```
Result {#164 ▼
  #attributes: array:17 [▼
    "isMobile" => false
    "isTablet" => false
    "isDesktop" => true
    "isBot" => false
    "browserFamily" => "HiSoRange Generic Browser"
    "browserVersionMajor" => 0
    "browserVersionMinor" => 0
    "browserVersionPatch" => 0
    "osFamily" => "HiSoRange Generic OS"
    "osVersionMajor" => 0
    "osVersionMinor" => 0
    "osVersionPatch" => 0
    "deviceFamily" => ""
    "deviceModel" => ""
    "mobileGrade" => ""
    "cssVersion" => 0
    "javaScriptSupport" => true
  ]
}
```

I tried it with Google Chrome and Firefox (both latest Windows versions), same result.

Is there anything I'm missing?

Using Laravel 5.3

thanks!

**Comment by mohammad-69** [comment]
same thing here I just get HiSoRange Generic Browser in laravel 5.3 when testing on windows 10

**Comment by omkarok2390** [comment]
i am getting same output. my output is
{
isMobile: false,
isTablet: false,
isDesktop: true,
isBot: false,
browserFamily: "HiSoRange Generic Browser",
browserVersionMajor: 0,
browserVersionMinor: 0,
browserVersionPatch: 0,
osFamily: "HiSoRange Generic OS",
osVersionMajor: 0,
osVersionMinor: 0,
osVersionPatch: 0,
deviceFamily: "",
deviceModel: "",
mobileGrade: "",
cssVersion: 0,
javaScriptSupport: true
}

i am using laravel 5.2. i have added  package "hisorange/browser-detect": "2.*". and also added hisorange\BrowserDetect\Provider\BrowserDetectService::class,
and
'BrowserDetect' => hisorange\BrowserDetect\Facade\Parser::class,
in app.php.
i am using win 10 OS. 
i have also check using 
    return \BrowserDetect::detect('Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36');
and
    return \BrowserDetect::detect($request->header('User-Agent'));
but getting same output.

Is there anything I'm missing?

Thanks

**Comment by martingg88** [comment]
Yes. Same issue for Laravel 5.3. Any idea. Thanks.

**Comment by jbardnz** [comment]
I am having the same issue as well in Laravel 5.3 - running locally and on my production server.

**Comment by Bashilor** [comment]
same here; Laravel 5.4 on W10 & Debian 8

**Comment by kjskjs** [comment]
Same issue for Laravel 5.1 too. Any clues?

**Comment by WarrenGIT** [comment]
Having the same issue with Laravel 5.4 - looking out for a fix hopefully soon.

**Comment by shweta-mydreamholiday** [comment]
anyone solved this issued? I am facing same problem. thanks.

**Comment by idanpt** [comment]
same here. Laravel 5.3

**Comment by riquedev** [comment]
same here; Laravel 5.4 on W10

**Comment by ArmeniaH** [comment]
Same here, Latest laravel on W10 on Internet Explorer

**Comment by CarlosGHRS** [comment]
One more with the same issue, Laravel 5.2 and Win 10

**Comment by victorybiz** [comment]
Have same issue, Laravel 5.5 on Win10

**Comment by hisorange** [comment]
#76

**Comment by jimmy8269** [comment]
how to get 'userAgent' value only
