### ISSUE TITLE
Problem when installing Laravel 5.4

### ISSUE THREAD

**Issue by jerauf** [hisorange/browser-detect#60]
When I updated to Laravel 5.4, I get this error when trying to vendor:publish:

```
  [Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share() 

```
And I get this error in my browser:

```
FatalErrorException in BrowserDetectService.php line 48:
Call to undefined method Illuminate\Foundation\Application::share()
```

What could this be? It has to do with this package because I did a fresh install without browser-detect and I have no problems.

**Comment by hisorange** [comment]
Fixed by the latest PR

**Comment by jerauf** [comment]
PR?
