### ISSUE TITLE
showing safari , in chorme device toolbar 

### ISSUE THREAD

**Issue by shrikant190890** [hisorange/browser-detect#61]
when i am testing it in to normal mode of chorme browser is showing chorme this is right but when i testing it into chorme device toolbar (iPhone 6s) it is showing safari. i tested many more package but this issue is showing in all packages and also in this package

**Comment by ricardocino** [comment]
The standard browser on a Iphone 6s is safari and google chrome is just 'emulating' the mobile device, so showing that the browser is 'safari' is normal.

**Comment by hisorange** [comment]
#76
