### ISSUE TITLE
Error on Laravel 5.4

### ISSUE THREAD

**Issue by quinhone** [hisorange/browser-detect#62]
local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::share()' in C:\myProject\vendor\hisorange\browser-detect\src\Provider\BrowserDetectService.php:48

Please! How can I solve this?

**Comment by hisorange** [comment]
Pull the newest version, already fixed in it.
