### ISSUE TITLE
Compatibility with Laravel 5.4

### ISSUE THREAD

**Issue by kulbakin** [hisorange/browser-detect#66]
Doesn't work in Laravel 5.4 due to `share` method removed from `$app` container

**Comment by Spyker888** [comment]
From migration guide to [laravel 5.4](https://laravel.com/docs/5.4/upgrade) **share** method should be removed by **singleton**. 

In your case in file **/vendor/hisorange/browser-detect/src/Provider/BrowserDetectService.php** you need to make some changes in function **registerParser()** 
from: 
`$this->app['browser-detect.parser'] = $this->app->share(function($app) {
			return new Parser($app);
});`
to:
`$this->app['browser-detect.parser']	= $this->app->singleton('parser',function($app) {
			return new Parser($app);
		});`

In my case it helps and i don't see errors anymore.

**Comment by nerdalertdk** [comment]
After this change i get this error

```
RuntimeException in Facade.php line 218:
A facade root has not been set.
```

**Comment by desh901** [comment]
Any update regarding laravel 5.4 compatibility?

**Comment by andytriboletti** [comment]
I tried to fix this yesterday but ended up going with Agent. https://github.com/jenssegers/agent

**Comment by polyma** [comment]
Should be fixed by https://github.com/hisorange/browser-detect/pull/68

**Comment by aakarim** [comment]
Should be fixed by https://github.com/hisorange/browser-detect/pull/68

**Comment by hisorange** [comment]
#76
