### ISSUE TITLE
A facade root has not been set exception

### ISSUE THREAD

**Issue by SkifAlef** [hisorange/browser-detect#67]
Laravel 5.4

**A facade root has not been set.** exception is throwing when I'm trying to execute `\BrowserDetect::detect()`

I've changed config/app.php to include
```
"providers" => [
    ...
    hisorange\BrowserDetect\Provider\BrowserDetectService::class,
]
```
and
```
"aliases" => [
    ...
    'BrowserDetect' => hisorange\BrowserDetect\Facade\Parser::class,
]
```

Also my IDE highlights `detect()` function as non-existing.

**Comment by Uhelliton** [comment]
I'm having the same problems ?

**Comment by hisorange** [comment]
#76
