### ISSUE TITLE
是不是不使用与L5.2？

### ISSUE THREAD

**Issue by maxing1005** [hisorange/browser-detect#69]
我用的是L5.2，使用您的工具后，发现报错，报错找不到相应的类，我不知道该怎么处理，如果L5.2可以使用的话，您可以给我一个在控制器中使用的方式的例子吗？

**Comment by hisorange** [comment]
Sorry I can't even display what you wrote just squares everywhere :cry:

**Comment by ThaDafinser** [comment]
![image](https://user-images.githubusercontent.com/533017/27690114-af8ede30-5ce0-11e7-8949-0cbeb80efbc5.png)

**Comment by hisorange** [comment]
@maxing1005 Sure, send me backtrace hisoranger@gmail.com

**Comment by hisorange** [comment]
#76
