### ISSUE TITLE
Disabling auto update doesn't work

### ISSUE THREAD

**Issue by rogan-son** [hisorange/browser-detect#70]
I set 'doAutoUpdate' to 'false' to turn off auto update.
But, it seems like still trying to update automatically.
Can you help me to disable this option?

hisorange/browser-detect/src/config/plugins.php
'doAutoUpdate' 	=> false

**Comment by mbezhanov** [comment]
@rogan-son did you clear your config cache (`php artisan config:clear`) after setting `'doAutoUpdate' => false`?

**Comment by hisorange** [comment]
#76
