### ISSUE TITLE
memory problem with phpbrowscap dependency

### ISSUE THREAD

**Issue by quinhone** [hisorange/browser-detect#71]
Allowed memory size of 33554432 bytes exhausted (tried to allocate 26476509 bytes) in /vendor/garetjax/phpbrowscap/src/phpbrowscap/Browscap.php

**Comment by bfblackjack** [comment]
I am also encountering this issue.

FatalErrorException in Browscap.php line 961:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 62914584 bytes)

**Comment by mbezhanov** [comment]
@quinhone  Increasing your php.ini `memory_limit` to about `256M` should do the trick - not really a long-term solution, but should solve your problem for the time being.

It will definitely be great if the memory usage of this library can be optimized.

**Comment by hisorange** [comment]
#76
