### ISSUE TITLE
Incorrect browser name

### ISSUE THREAD

**Issue by felipefreitasnet** [hisorange/browser-detect#79]
Hello, I was doing some tests and I found a probable problem.

I'm using:

Platform: **Windows Phone**  
Browser: **Edge**
UserAgent: Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; RM-1067) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.15063

But it is returning:

Platform: **Windows Phone**   _(correct)_
Browser: **Chrome 15.15063** _(wrong)_

It is capturing the first occurrence of the browser name, and the last browser version, look:

Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; RM-1067) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome**/52.0.2743.116 Mobile Safari/537.36 Edge/**15.15063**

What can it be?

... sorry for my English

**Comment by hisorange** [comment]
Let me just save this case, the problem here is: there is no regulation how the user agent string is formated, every browser every version has some different string there without a standard or a logic.

I belive we can catch many edge case with browscap but its quite slow and big database. So maybe in the 3.1.0 version where the native get_browser is implemented.

**Comment by hisorange** [comment]
So, did a little research with this user agent string. First I thought, Oh the get_browser with a lot of user agent string will handle it, hmm sadly nope, recognizing the chrome string too.

But not everything is a goner! Found a library which is able to parse the right browser from, I mean kinda able [Piwick](https://github.com/piwik/device-detector) can recognize the edge even tho it can't parse the version or other things.

Already on the feature list to implement, but not today, I just wanted to give you an update on the situation. Sadly the piwick seems to be a huge library and a heavy load for implementation, but we will see if it's worth it or not.

Happy New Year!

**Comment by hisorange** [comment]
For why not, fixed in 3.1.0. You can pull that version now ^.^
