### ISSUE TITLE
Protected properties

### ISSUE THREAD

**Issue by wkornilow** [hisorange/browser-detect#83]
When I try to call BrowserDetect::detect() to get all available information I get object with protected properties and can't get a needed me values. I don't find any useful iinformation about this. I have the latest version 3.*

**Comment by hisorange** [comment]
You have public accessors for each property https://github.com/hisorange/browser-detect/blob/stable/src/Result.php, also in the readme you can read about every value and it's meaning.

If you need an array of informations call the toArray() on it ^.^
