### ISSUE TITLE
Can not allocate memory error

### ISSUE THREAD

**Issue by balmohan** [hisorange/browser-detect#85]
I am getting this error while installing this package. my configuration
PHP version - 7.2
OS-Ubuntu x64
RAM-1GB
SSD-25GB 
I have already tried by increasing memory_limit=-1 and 1000M. 
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 550510592) (tried to allocate 20480 bytes) in /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php on line 126

**Comment by hisorange** [comment]
Aye, there. So, you actually running out of memory, the  -1 means unlimited, and from the error it seems you have 525M available. And to the main question, you get the error because you conflict with other packages, if you paste your composer.json here we can have a look on it.
