### ISSUE TITLE
Error Call to undefined method offsetGet() using Directives in Blade templates

### ISSUE THREAD

**Issue by franklin-vidal** [hisorange/browser-detect#86]
I use the following directive in blade template in Laravel 5.6.3 and PHP 7.2:
```
@desktop
    <p>Content</p>
@enddesktop
```
And get error:

> "Call to undefined method hisorange\BrowserDetect\Result::offsetGet()"

**Comment by hisorange** [comment]
Thanks for the report, found the cause will be releasing a patch pretty soon.

**Comment by hisorange** [comment]
Got it released in v3.1.4, cheers!
