### ISSUE TITLE
Custom directives do not work in Laravel 5.6.3 with PHP 7.2

### ISSUE THREAD

**Issue by Robthegod23** [hisorange/browser-detect#88]
I'm attempting to use the mobile directive in one of my blade templates as such:

```
<div>
 @mobile
   THIS IS MOBILE
@else 
    THIS IS NOT MOBILE
@endmobile
</div>
```

However I get the following error:

> ErrorException (E_ERROR)
> Parse error: syntax error, unexpected 'else' (T_ELSE), expecting end of file (View: /home/vagrant/www/app/resources/views/home.blade.php)

I believe the directive creation code may be broken... a fix would be much appreciated!

**Comment by Soft-me** [comment]
Same problem ,and I'm attempting to use the mobile directive in my controller as such:
```
public function index()
    {
        var_dump(Browser::isMobile());
        var_dump(Browser::isTablet());
        var_dump(Browser::isDesktop());
        die();
        return view('home');
    }
```
I get the following error:

> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'App\Http\Controllers\Browser' not found

I think maybe just I forget add `use path\to\browser-detect` , but when I type code my phpstorm doesn't show tip in live template。Did I miss something ?

**Comment by hisorange** [comment]
@Wayne-jp 

You don't have the Browser class imported.
Simply add the line:
`use Browser;`

---
*As a side note, PHPStorm can't detect facades, if you have autocompletion on laravel's native facades those are either made by a package or you imported the IDE setting for it.*

**Comment by hisorange** [comment]
Made a possible fix, will test is tomorrow at home, it should fix it. Already pullable @staging branch.

**Comment by Bing1024** [comment]
yeah
