### ISSUE TITLE
Blade directives do not get parsed

### ISSUE THREAD

**Issue by mihaiconstantin** [hisorange/browser-detect#89]
I tried using some of the directives from the `README.md` on a fresh Laravel `5.5.*` install and they don't get parsed. For instance, writing the following in `welcome.blade.php` prints the entire string (i.e., including `@desktop`) and the condition is not run:

```
@desktop
    This is the MOBILE template!
@enddesktop
```

I also tried adding the service provider and the class alias to `config/app.php` without success.
Do you know what the problem may be?
Thanks for this very useful package.

**Comment by hisorange** [comment]
Thanks for reporting, it's the same issue as #88 will be fixed soon, an unexpected breaking change was introduced in laravel 5.5 ish, or at least connected to the api what the package using to define the directives, will be patched at the next release.
