### ISSUE TITLE
Support laravel 5.7

### ISSUE THREAD

**Issue by testdnmedia** [hisorange/browser-detect#95]
Problem 1
    - The requested package laravel/framework 5.7.* is satisfiable by laravel/framework[5.7.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
    - hisorange/browser-detect 3.1.4 requires laravel/framework ~5.0 -

**Comment by mikkellindblom** [comment]
Any news here?

**Comment by Hesesses** [comment]
same here
